 export const GET_USERS_START = "GET_USERS_START"
 export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
 export const GET_USERS_FAIL = "GET_USERS_FAIL"

 export const DELETE_USER_START = "DELETE_USER_START"
 export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
 export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

 export const ADD_USER_START = "ADD_USER_START"
 export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
 export const ADD_USER_FAIL = "ADD_USER_FAIL"

 export const EDIT_USER_START = "EDIT_USER_START"
 export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"
 export const EDIT_USER_FAIL = "EDIT_USER_FAIL"